### ISSUE TITLE
Change Menu Items in ENgage

### ISSUE THREAD

**Issue by ncadjan** [arckinteractive/en-issues#44]
Break out Events to two different menu items
1. Agendas - with the option to register.  It should show the meetings the member is invited to and then all the meetings.  Ones they are invited to would show up with the ability to register.  Other meetings would be Request Invitation (like we have it now) I think this should display the Event Pages associated with these meetings
2. Meeting Summaries  This would be the Event Pages for meetings that have been completed and their resources.

**Comment by beck24** [comment]
2 pages:

Agendas - upcoming events
tab1 - "invited" - events the user has been invited to
tab2 - "all" - all events the user has permission to see

Event Summaries - past events
tab1 - "mine" - events the user was invited to in the past
tab2 - "all" - all events in the past the user has permission to see

**Comment by sang-entech** [comment]
2 pages

**AGENDAS** - upcoming events (ALL FUTURE DATES)
Tab 1 - "My Invites" - events the user have been invited to
(SORT) Ascending by Date
Button 1 - "Register" - to the event

Tab 2 - "All" - all events the user has permission to see (SORT ASC)
(SORT) Ascending by Date
Button 2 - "Request Invitation" - to the event (NEW function in ENgage)
(If you have time to complete this button functionality before Tues (02/06), otherwise just SHOW all events for now.)


**MEETING HISTORY** - past events (LAST 6 MONTHS?? LAST 1 YEAR??)
Tab 1 - "My Meetings" - events the user was invited to in the past
(SORT) Descending by Date

Tab 2 - "All" - all events in the past the user has permission to see
(SORT) Descending by Date
(FILTER/SHOW) 10 meetings at a time
(Bottom of Page) Button 1 - "Load More" - load next 10 meetings that user has permission to see
?? Button 2 - "Filter" by Network (might be overkill)

We will try to get more defined date parameters from leadership.
