### ISSUE TITLE
Debug Issue

### ISSUE THREAD

**Issue by sang-entech** [arckinteractive/en-issues#47]
## **Debug Issue - Hyperlink breaks external action call.**

On Android 7.0 with ENgage app version 1.7.2, hyperlink does nothing and breaks any further external action call.

**EXAMPLE 1:**
Experts > Anna Tavis  |  Clicking on "Read More..." link does nothing. However, once that link is clicked, "Contact ND" button stops working.
 
![link - read more2](https://user-images.githubusercontent.com/35508395/36474865-de464434-16c6-11e8-9639-56963a886ac0.png)

**EXAMPLE 2:**
Events > Test Recording with IS  |  Clicking on "Click the Recording below to Listen." link does nothing. Same as Example 1, once that link is clicked, "Contact ND" button stops working. 

![link - recording2](https://user-images.githubusercontent.com/35508395/36474871-e42f65ec-16c6-11e8-95d1-5610b3ed40ee.png)

**PHONE INFO:**
Carrier: Verizon Wireless
Model #: SM-G930V (Samsung Galaxy S7)
Android: 7.0
Build #: NRD90M.G930VVRS4BRA1

Security Software Version:
MDF v3.0 Release 1
WLAN v1.0 Release 1
VPN v1.4 Release 8.2
ASKS v1.4 Release 161228
SMR Jan-2018 Release MS

**APP INFO**
Version: 1.7.2

**Comment by beck24** [comment]
This is likely due to the fact that those links are not generated by the app, but are in the html of the site that is being re-rendered within the app.  I'll have to play around with them to see if there's anything I can do the make them functional, but for something like "click the recording to listen" if it's just a link to the resource page it won't work anyway because the target URL requires you to be logged in.  Being logged in within the app is completely different than being logged in on the site.
